services:
  cardano-node-ogmios:
    image: cardanosolutions/cardano-node-ogmios:v6.13.0_10.1.4-${NETWORK}
    logging:
      driver: json-file
      options:
        max-size: 400k
        max-file: "20"
    ports:
      - ${OGMIOS_PORT:-1337}:1337
      - ${CARDANO_PORT:-3000}:3000
    volumes:
      - node-db:/db
      - node-ipc:/ipc
    restart: on-failure

  kupo:
    image: cardanosolutions/kupo:v2.11.0
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    ports:
      - ${KUPO_PORT:-1442}:1442
    command: [
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/cardano-node/config.json",
      "--since", "${KUPO_SINCE:-origin}",
      "--match", "${KUPO_MATCH:-*}",
      "--workdir", "/db",
      "--host", "0.0.0.0",
      "--port", "1442"
    ]
    volumes:
      - kupo-db:/db
      - node-ipc:/ipc
      - ./config/cardano-configurations/network/${NETWORK}:/config

  rapidoc-kupo:
    build:
      context: .
      target: rapidoc-kupo
    ports:
      - ${RAPIDOC_KUPO_PORT:-2600}:2600
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: "10"

  rapidoc-ogmios:
    build:
      context: .
      target: rapidoc-ogmios
    ports:
      - ${RAPIDOC_OGMIOS_PORT:-2500}:2500
    restart: on-failure
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: "10"

volumes:
  node-db:
  node-ipc:
  kupo-db:
